### ISSUE TITLE
Indexing the DepCC with ES

### ISSUE THREAD

**Issue by alexanderpanchenko** [eugenso/josimtext#1]
Motivation
==========

The goal is to enable a wide range of NLP applications with the DepCC corpus by indexing it, e.g. information extraction or relation extraction, etc.

Implementation
============

What should be indexed
------------------

- full texts of the sentences (default morph. analyzer)
- dependencies (all fields of the CoNLL file)

Prototype
---------

To enable quick and distributed indexing Spark + ES combination should be used. The result of this work is a Spark job formatted in the same was as other jobs in this repository, consisting of 3 files: 

1. Source of the job e.g.: https://github.com/uhh-lt/josimtext/blob/master/src/main/scala/de/uhh/lt/jst/corpus/ReformatConll.scala 
 
2. Test of the job e.g.: https://github.com/uhh-lt/josimtext/blob/master/src/test/scala/de/uhh/lt/jst/corpus/ReformatConllTest.scala 

3. A bash script to run the job e.g.: https://github.com/uhh-lt/josimtext/blob/master/scripts/reformat-conll.sh

This presentation presents some code snippets on how to use ElastiSearch from Spark.

https://www.elastic.co/elasticon/conf/2017/sf/what-is-the-scoop-on-es-hadoop-spark-streaming-and-more?ultron=elasticon&blade=facebook&hulk=cpc

![image](https://user-images.githubusercontent.com/1456830/32009937-afec0d26-b9b0-11e7-96bc-40b27cb4c11a.png)

A tutorial with more code samples is available here: https://www.elastic.co/guide/en/elasticsearch/hadoop/master/spark.html 

![image](https://user-images.githubusercontent.com/1456830/32010087-1c4cfa16-b9b1-11e7-8ebd-9bbc98834a27.png)

ElasticSearch Installation
------------------------

For the first time (testing / debuggin) installation on one node e.g. headnode is OK. 

Data Paths
-----------

All 2.4 Tb of the input files live in: 
panchenko@ltheadnode:$ hdu /user/panchenko/corpora/depcc-conll/

For tests, use just one / several files from this directory.

**Comment by alexanderpanchenko** [comment]
https://db-blog.web.cern.ch/blog/prasanth-kothuri/2016-05-integrating-hadoop-and-elasticsearch-%E2%80%93-part-2-%E2%80%93-writing-and-querying

**Comment by alexanderpanchenko** [comment]
https://discuss.elastic.co/t/is-it-possible-to-perform-bulk-insert-from-spark-to-elasticsearch/25174/2

**Comment by alexanderpanchenko** [comment]
https://github.com/uhh-lt/josimtext/blob/master/src/main/scala/de/uhh/lt/jst/corpus/Conll2Texts.scala

**Comment by eugenso** [comment]
It is working now, try class de/uhh/lt/jst/corpus/StoreToElasticSearch.scala
